name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug - List dist contents
        run: |
          echo "Contents of dist folder:"
          ls -R dist
          echo "Contents of dist/index.html:"
          cat dist/index.html

      - name: Create .nojekyll file
        run: touch dist/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true

      - name: Debug - Print GitHub Pages URL
        run: |
          echo "Your site should be available at: https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
        if: success()